altsyncram #(.address_aclr_a( "UNUSED" ),
#key:t.v
# --
	     .address_aclr_b( "NONE" ),
	     .address_reg_b( "CLOCK1" ),
	     .byte_size( 8 ),
	     .byteena_aclr_a( "UNUSED" ),
	     .byteena_aclr_b( "NONE" ),
	     .byteena_reg_b( "CLOCK1" ),
	     .clock_enable_core_a( "USE_INPUT_CLKEN" ),
	     .clock_enable_core_b( "USE_INPUT_CLKEN" ),
	     .clock_enable_input_a( "NORMAL" ),
	     .clock_enable_input_b( "NORMAL" ),
	     .clock_enable_output_a( "NORMAL" ),
	     .clock_enable_output_b( "NORMAL" ),
	     .intended_device_family( "unused" ),
	     .ecc_pipeline_stage_enabled( "FALSE" ),
	     .enable_ecc( "FALSE" ),
	     .implement_in_les( "OFF" ),
	     .indata_aclr_a( "UNUSED" ),
	     .indata_aclr_b( "NONE" ),
	     .indata_reg_b( "CLOCK1" ),
	     .init_file( "UNUSED" ),
	     .init_file_layout( "PORT_A" ),
	     .maximum_depth( 0 ),
	     .numwords_a( 0 ),
	     .numwords_b( 0 ),
	     .operation_mode( "BIDIR_DUAL_PORT" ),
	     .outdata_aclr_a( "NONE" ),
	     .outdata_aclr_b( "NONE" ),
	     .outdata_reg_a( "UNREGISTERED" ),
	     .outdata_reg_b( "UNREGISTERED" ),
	     .power_up_uninitialized( "FALSE" ),
	     .ram_block_type( "AUTO" ),
	     .rdcontrol_aclr_b( "NONE" ),
	     .rdcontrol_reg_b( "CLOCK1" ),
	     .read_during_write_mode_mixed_ports( "DONT_CARE" ),
	     .read_during_write_mode_port_a( "NEW_DATA_NO_NBE_READ" ),
	     .read_during_write_mode_port_b( "NEW_DATA_NO_NBE_READ" ),
	     .stratixiv_m144k_allow_dual_clocks( "ON" ),
	     .width_a( 1 ),
	     .width_b( 1 ),
	     .width_byteena_a( 1 ),
	     .width_byteena_b( 1 ),
	     .width_eccstatus( 3 ),
	     .widthad_a( 1 ),
	     .widthad_b( 1 ),
	     .wrcontrol_aclr_a( "UNUSED" ),
	     .wrcontrol_aclr_b( "NONE" ),
	     .wrcontrol_wraddress_reg_b( "CLOCK1" ),
	     .lpm_type( "altsyncram" ),
	     .lpm_hint( "unused") 
	     ) U_ALTSYNCRAM(
			    .aclr0( aclr0 ),
			    .aclr1( aclr1 ),
			    .address_a( address_a ),
			    .address_b( address_b ),
			    .addressstall_a( addressstall_a ),
			    .addressstall_b( addressstall_b ),
			    .byteena_a( byteena_a ),
			    .byteena_b( byteena_b ),
			    .clock0( clock0 ),
			    .clock1( clock1 ),
			    .clocken0( clocken0 ),
			    .clocken1( clocken1 ),
			    .clocken2( clocken2 ),
			    .clocken3( clocken3 ),
			    .data_a( data_a ),
			    .data_b( data_b ),
			    .eccstatus( eccstatus ),
			    .q_a( q_a ),
			    .q_b( q_b ),
			    .rden_a( rden_a ),
			    .rden_b( rden_b ),
			    .wren_a( wren_a ),
			    .wren_b( wren_b ) );




