#!/usr/bin/perl -w
use File::Basename;
use File::Copy;
print "missing param\n" if @ARGV==0;
@a=glob "$ARGV[0]*.v";

for $a ( @a ) {
  ( $filename , $suffix ) = split( /\./ , basename( $a ) );
  $destfile = "/home/agump/.emacs.d/emacs_mode/yasnippet/yasnippet-0.6.1c/snippets/text-mode/verilog-mode/xilinx_verilog_unisim/xilinx_$filename"; 
  open FID, ">$destfile";
  print FID  "#contributor : Aaron-generated by script\n";
  print FID  "#name : xilinx_$filename\n";
  print FID  "# --\n";
  print FID  "$filename U_$filename(/*AUTOINST*/);\n";
}



